export const metadata = {
  title: 'Nextwaves Tech',
  description: 'Generated by Next.js',
}
import '../Styles/global.css';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
